export PATH=$PATH:~/go/bin
export PATH=$PATH:~/.local/bin


PROMPT='%F{46}%* %F{blue}%m:%F{214}%C%f> '




# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
# if present, source any work-related config
if [ -f ~/.work_config ]; then
	. ~/work_config
fi

# Example aliases
alias dropbox='cd ~/Dropbox/'
alias la='ls -a'
alias ld='ls -d */'
alias ll='ls -lh'
alias ls='ls -G'
alias projects='cd ~/Projects'
alias py='python3'
alias reload="source ~/.zprofile"
alias reload='source ~/.zshrc'
alias rm='rm -i'
alias tmux_config='vim ~/.tmux.conf'
alias vim="nvim"
alias vim='nvim'
alias wp="cd ~/workplace"
alias zshrc="vim ~/.zshrc && reload"
alias zshrc='vim ~/.zshrc && source ~/.zshrc'
