alias rm='rm -i'
alias dropbox='cd ~/Dropbox/'
alias py='python3'
alias vim='nvim'
alias ls='ls -G'
alias la='ls -a'
alias ll='ls -lh'
alias ld='ls -d */'
alias zshrc='vim ~/.zshrc && source ~/.zshrc'
alias tmux_config='vim ~/.tmux.conf'
alias projects='cd ~/Projects'
alias reload='source ~/.zshrc'

PROMPT='%F{46}%* %F{blue}%m:%F{214}%C%f> '


